name: Build and commit docs to main

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    # prevent workflow from running for commits created by this workflow
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add, commit, and push the generated docs folder back to main.
          git add docs || true
          git diff --staged --quiet || (git commit -m "chore(docs): update generated docs [skip ci]" && git push origin HEAD:main)
